# Generated by Django 5.2.11 on 2026-09-13 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_automation', '0002_channelverification_delete_telegrambot'),
        ('workspaces', '0002_backfill_personal_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelverification',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='channelverification',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_channel_verifications', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_telegram_channels', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='telegrampublishlog',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='telegrampublishlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_telegram_publish_logs', to='workspaces.workspace'),
        ),
    ]
