# Generated by Django 5.2.11 on 2026-04-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_main_keywords_campaign_main_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='tag',
            field=models.CharField(choices=[('seo', 'SEO'), ('blog', 'Blog'), ('product', 'Product'), ('social', 'Social'), ('education', 'Education')], default='product', max_length=50),
        ),
    ]
