# Generated by Django 5.2.11 on 2026-04-07 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_keyword_campaign_campaign_tag'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='content_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='content.contentitem'),
            preserve_default=False,
        ),
    ]
