# Generated by Django 5.2.11 on 2026-04-07 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_keyword_content_item'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaigngoal'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CampaignFormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('schema_json', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.platform')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaigngoal')),
            ],
            options={
                'unique_together': {('goal', 'platform', 'version')},
            },
        ),
    ]
