# Generated by Django 5.2.11 on 2026-04-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaigngoal_campaign_goal_campaignformschema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigngoal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
