# Generated by Django 5.2.11 on 2026-04-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaigngoal_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignformschema',
            unique_together={('goal', 'version')},
        ),
        migrations.RemoveField(
            model_name='campaignformschema',
            name='platform',
        ),
    ]
