# Generated by Django 5.2.11 on 2026-04-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaignformschema_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
