# Generated by Django 5.2 on 2026-09-13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ('name', 'id')},
        ),
        migrations.CreateModel(
            name='WorkspaceFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('contributor', 'Contributor'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={'ordering': ('workspace_id', 'user_id')},
        ),
        migrations.CreateModel(
            name='PolicyGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('contributor', 'Contributor'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], max_length=16)),
                ('action', models.CharField(max_length=120)),
                ('effect_class', models.CharField(choices=[('read', 'Read'), ('draft', 'Draft'), ('mutate_internal', 'Mutate internal'), ('consequential', 'Consequential')], max_length=20)),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspace_policy_grants', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_grants', to='workspaces.workspace')),
            ],
            options={'ordering': ('workspace_id', 'role', 'action')},
        ),
        migrations.AddConstraint(
            model_name='workspacefeatureflag',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='workspace_unique_feature_flag'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='workspace_unique_membership'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('is_active', True), _connector='OR'), name='workspace_default_membership_active'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='workspace_one_default_per_user'),
        ),
        migrations.AddConstraint(
            model_name='policygrant',
            constraint=models.UniqueConstraint(fields=('workspace', 'role', 'action'), name='workspace_unique_role_action_grant'),
        ),
    ]
