# Generated by Django 5.2.11 on 2026-04-07 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_remove_keyword_campaign_campaign_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_keyword', models.CharField(max_length=100)),
                ('additional_keywords', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(default='website', max_length=50)),
                ('language', models.CharField(default='fa', max_length=20)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('researching', 'Researching'), ('research_done', 'Research Done'), ('outlining', 'Outlining'), ('outline_done', 'Outline Done'), ('generating', 'Generating'), ('completed', 'Completed')], default='idle', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
                ('model_used', models.CharField(max_length=100)),
                ('rag_context_used', models.JSONField(default=dict)),
                ('generation_metadata', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='content.contentitem')),
            ],
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.contentitem')),
            ],
        ),
        migrations.CreateModel(
            name='OutlineSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('level', models.IntegerField()),
                ('order', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.outline')),
            ],
        ),
    ]
