# Generated by Django 5.2.11 on 2026-04-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='information',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='goal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
