# Generated by Django 5.2.11 on 2026-04-08 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentitem_information_alter_contentitem_goal'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('schema', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_schemas', to='platforms.platform')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('platform', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ContentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_form', to='content.contentitem')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='content.contentformschema')),
            ],
        ),
    ]
