# Generated by Django 5.2.11 on 2026-04-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentformschema_contentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('is_proccessed', models.BooleanField(default=False)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contentitem')),
            ],
        ),
    ]
