# Generated by Django 5.2.11 on 2026-04-11 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='is_proccessed',
        ),
        migrations.AddField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='content.contentitem'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=50),
        ),
    ]
