# Generated by Django 5.2.11 on 2026-04-13 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_keyword_is_proccessed_keyword_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentform',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='content.contentformschema'),
        ),
    ]
