# Generated by Django 5.2.11 on 2026-04-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_contentform_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='search_source',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
