# Generated by Django 5.2.11 on 2026-04-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentitem_search_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateContentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
