# Generated by Django 5.2.11 on 2026-04-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_createcontentstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='step',
            field=models.CharField(default='research', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontentstep',
            name='content_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.contentitem'),
            preserve_default=False,
        ),
    ]
