# Generated by Django 5.2.11 on 2026-05-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_contentitem_step_createcontentstep_content_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='title',
            field=models.CharField(default='untitled', max_length=200),
        ),
    ]
