# Generated by Django 5.2.11 on 2026-05-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_delete_keyword'),
        ('content', '0011_aichatsession_aimessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aichatsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='aimessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='content_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contentitem'),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='main_keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
