# Generated by Django 5.2.11 on 2026-05-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_delete_keyword'),
        ('content', '0012_alter_aichatsession_options_alter_aimessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
    ]
