# Generated by Django 5.2.11 on 2026-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_contentitem_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='platform',
            field=models.CharField(blank=True, default='website', max_length=50, null=True),
        ),
    ]
