# Generated by Django 5.2.11 on 2026-05-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_contentitem_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
