# Generated by Django 5.2.11 on 2026-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_aimessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
