# Generated by Django 5.2.11 on 2026-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_aimessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
