# Generated by Django 5.2.14 on 2026-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_contentitem_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='auto_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='publish_immediately',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='publish_status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('researching', 'Researching'), ('research_done', 'Research Done'), ('outlining', 'Outlining'), ('outline_done', 'Outline Done'), ('generating', 'Generating'), ('completed', 'Completed'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('publish_failed', 'Publish Failed')], default='idle', max_length=50),
        ),
    ]
