# Generated by Django 5.2.14 on 2026-06-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_contentitem_auto_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('idle', 'Idle'), ('researching', 'Researching'), ('research_done', 'Research Done'), ('outlining', 'Outlining'), ('outline_done', 'Outline Done'), ('generating', 'Generating'), ('completed', 'Completed'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('publish_failed', 'Publish Failed')], default='idle', max_length=50),
        ),
    ]
