# Generated by Django 5.2.11 on 2026-09-13 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_aichatsession_public_id_aichatsession_workspace_and_more'),
        ('workspaces', '0003_backfill_legacy_workspaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsession',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
