# Generated by Django 5.2.11 on 2026-09-13 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_platform_is_active'),
        ('workspaces', '0002_backfill_personal_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_social_accounts', to='workspaces.workspace'),
        ),
    ]
