# Generated by Django 5.2.11 on 2026-09-13 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_socialaccount_public_id_socialaccount_workspace'),
        ('workspaces', '0003_backfill_legacy_workspaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
