# Generated by Django 5.2.11 on 2026-09-13 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aijob_media_type_aijob_metadata_aijob_parent_job_and_more'),
        ('workspaces', '0002_backfill_personal_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewsession',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_ai_interview_sessions', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='aijob',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='aijob',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_ai_jobs', to='workspaces.workspace'),
        ),
    ]
