# Generated by Django 5.2.11 on 2026-09-13 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aiinterviewsession_public_id_and_more'),
        ('workspaces', '0003_backfill_legacy_workspaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
