# Generated by Django 5.2.11 on 2026-04-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsource',
            name='sources_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
